### ISSUE TITLE
Choco and not PSGallery

### ISSUE THREAD

**Issue by jkavanagh58** [mmanela/PsAzureDevOps#5]
Just curious why this isn't in the PSGallery, I mean install-module would make more sense than install-package

**Comment by mmanela** [comment]
@jkavanagh58  Honestly, I just didn't know about PSGallery when I wrote this :) 

I will look at that for a future change

**Comment by mmanela** [comment]
I just published to PSGallery https://www.powershellgallery.com/packages/PsAzureDevOps/0.3.0
